//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountCode
    {
        public int DiscountID { get; set; }
        public string Code { get; set; }
        public int DiscountPercentage { get; set; }
        public System.DateTime ExpiryDate { get; set; }
    }
}
