//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int OrderID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public decimal TotalAmount { get; set; }
        public string PaymentMethod { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual User User { get; set; }


        public IOrderState State { get; set; }
        public void SetState(IOrderState newState)
        {
            // Nếu trạng thái hiện tại là "Đã giao", không thay đổi trạng thái
            if (Status == "Da giao")
            {
                throw new InvalidOperationException("Không thể thay đổi trạng thái khi đơn hàng đã giao.");
            }

            // Nếu trạng thái hiện tại là "Giao hàng thất bại", không thay đổi trạng thái
            if (Status == "Giao hang that bai")
            {
                throw new InvalidOperationException("Không thể thay đổi trạng thái khi đơn hàng đã thất bại.");
            }

            // Cập nhật trạng thái của đơn hàng
            State = newState;
            State.Handle(this); // Gọi phương thức Handle để xử lý hành động cho trạng thái mới
        }
    }
}
